name: xq-llm
# 触发workflow的条件
on:
    push:
        # 只有main分支发生push事件时，才会触发workflow
        branches: [main]
    pull_request:
        branches: [main]

env:
    SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
    SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
    USER_NAME: ${{ secrets.USER_NAME }} # 服务器用户名
    cache-name: note

# jobs表示执行的一项或多项任务
jobs:
    build: # 任务的job_id，具体名称自定义，这里build代表打包
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        steps:

            - name: checkout
              uses: actions/checkout@main

            - name: Setup PNPM
              uses: pnpm/action-setup@latest # 推荐使用最新版本的动作以确保功能更新
              with:
                version: 10.x # 设定安装PNPM的10.x版本，x代表该系列的最新小版本

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 20.x # 指定安装Node.js的20.x版本，x为兼容的小版本更新
                cache: "pnpm" #启用缓存以加速后续的运行

            # 缓存依赖
            # - name: Cache nodemodules
            #   uses: actions/cache@v1
            #   env:
            #       cache-name: cache-node-modules
            #   with:
            #       # 需要缓存的文件的路径
            #       path: ./node_modules
            #       # 对缓存的文件指定的唯一标识
            #       key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
            #       # 用于没有再找目标key的缓存的backup选项
            #       restore-keys: |
            #           ${{ runner.os }}-build-${{ env.cache-name }}-
            #           ${{ runner.os }}-build-
            #           ${{ runner.os }}-

            # 装依赖
            - name: Install
              run: pnpm i 

            # 打包
            - name: Build Web
              run: pnpm build

            # 上传打包资源
            - name: Deploy Web
              uses: appleboy/scp-action@master
              with:
                  source: "dist/*"
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.USER_NAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  target: "/www/wwwroot/www.czstudio.tech/" # 服务器目标路径


          
